## unauthorized POST request
#POST https://localhost:7087/api/Hosts HTTP/1.1
#Content-Type: application/json
#Cookie: .AspNetCore.Identity.Application=CfDJ8Fa7dzYtaSxMnz3kSL77wNnt4xjjIn5yhOE4UGjDl7F9YvjoG4r6VblggY4QxwySAqSk3knY7Fxra_x8jjVTlWUr2oaNaca7oAhW1JydL5ym9x1ECQ9CvFjbXpW8PyHVTsgpeWzYd4Ral1u9VUvBXugB_6gN5INzLhGa_BcXV5LuwHyZH178bKS5MLxUbPCkmgqJrEQqsFwnMkIGaJ5d_2eSyqOQE8Y8DDwwQXrqwieVg9Vtai9ZEWa0RF8d3ig7jGDoWJ-Hd7fF3JELECx9W2xj_3bmX_8MwBFvHk2d4zUWVB3fgZqxlezEuuwupPqSRPKg8ar26gyPFLaEVsOFxunZPUYG1FJid43cl5OyrsHn0_pR5fzmiK6aumvknuiaiVU_vY4NJa1C-nHW3C-JNw21XqD1GVFhplqHaGYgScNqC79GTGXGCFLcdfQ65n-LaFTG1tA2l20SdCbYAXos415392lSFuoqJ0hZYekezZ3Q2nlkJq_7s6padD8Jz1X6SoE8i9rR6NLZvv3GnS6tTKU4AiE5r4B-jTTVFP6NkDOWX1CIOIvvhY34RZibACU_4EKqPxt-ZZ6lUFEWn4FlUww8yD5o3iisQVuA2GZ7xqfX_AF3dCMbDUz8Ljorv1P-MYSX7B3xJLQ8HjGjUQL_w2At4Wm7CMMMuptSViY7Kd1bk-24CMS3moIoDy05WmbkUbMtDuCQziUUc-ffpSPcjwsWjK0E-drxkSnt9mmq3WPmMq8GMv7tRQg-S1eQAaKzMEFMoIhUA-d6xsRfdgpLU1Omm4oCWOdu45D67XEdI1QpFyyWZtqWpPOkSAZFfOSIAznerjrHmptGpdQpn1lWFo8
#
#{
#    "name": "HostTest",
#    "YearFirstPublished": "2012",
#    "Rating": "5",
#    "Gender": "Male"
#}

PUT https://localhost:7087/api/Episodes/1 HTTP/1.1
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8Fa7dzYtaSxMnz3kSL77wNmLs8nQ7kJxAGQQvjxKfkmcv8M2uSUzoo9n9P-TtUvkDo59oimzs5OyzPRrqIZDAgPOGzOYnu7gznx5Pl_Kk5S6ADwG9dR-n5X1EiXbvwHcVTzLEr0-wJQOx7Z9tDh5bpP7C04G4GPD-YcMOtLBA9LyceOUQVQ5PnsdCDuxyc6lq1hAvp_L8EGvzioJbKbh4KRQuyuASPfUn2b85QruKspjXtYWvTJAUs_7ba3CNYYjSyw-zvjmm75ePwbYY4Be1gpYW3xNd6brOU2gtVQVcsDhqn92m5VQdBCA--yj2lqS01rYBpyJVkPwXHh5oVqmBId8xVYWNoBDu-1BapL9xdgMPwOxlu9Knqq4IUrN_aXqeUC5JvBSmwcBjUbIs5poQ6F0sCjtkVISBjuhvthGANztUKiMitXj3cLO4vWs1KIxfdd21dciJw7jnwzGpM1mp8rMvbmRA8HsIbGazsRLGLC4oQYTpnFA56v9EvNWLBG2k35CWWh8ahukcWKD1mDnRULfAqJmb_vb_nHoXB6sWe-YoTw06xJcr3tRnMPkCrcSWSmj7vJi4DS_pK_X3UQR4wrglsqvZX1yyXSSAjg4ODTxhrCL9Dks6dkGONB6dAXh60FI8W_uMoH8TtoyoI7YxMXhquyA9clxZxURPSc1Qk0lud6KsiVvIijLpG16OZcy5tzf1SFfZDjrDIjUh4PewbLo3fVy0D2dJM0TTZGJ1O8_wnBdP8jtY54C9_0SvZ39U17lKvdMGY1C6ev95K6OsZFC7x1s9_r6lut-xHjMZh0F5qobYwxh5opG60mWjsUKXC9jumGwgSF7345_Rfxr-DM

{
  "episodeId": 1,
  "listeners": 900000
}

