POST https://localhost:7087/Episode/Add/ HTTP/1.1
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8Fa7dzYtaSxMnz3kSL77wNkXg5m8aeA3UoTla9aLU1OHDuxP5hP0AzKuLsSTC8oc5d1Yo4FG4EZnvSWr0NkuFFO1FrIMGzArUKFKs42G4rLPGFwPF1RWQZlJoJKJuKWrwXjJHew0FsnueqaCnNIzBwv3XpG3tg--ZntNBfegXQ5T4Xx-c2hd8DGSXTeRlKNN7WXNNW5HdAOo5AdSvFGt7ySLEeChhLezAku9mlBsr35QjhkAAmNH3GSpZIDn_P_vDoj5TzobwOUJTSiu767uSwHtE_4QNHZRjI8gnicHa5UXqW-kmlpDDZwJzoovE4O2VgHtDifg-CzaySvXqDWrgAkglg26RYzU8yojQp8nyu_pXHEwsCiA00ZGYj_Y-GbAcsA_FO9TjLJI3-TO1gb_WTZJWLX-V9itbWLjGYUIi9ybQn1nUB2-lB1JuZtJgpQoh8wm4CWh1AWWi2lW7U8zLgSTdbrhkUPi87mLlg274V5gxIC1csIznTWifeNW7zLud2iQLhV9R7mVi2u_Ca16dSopAm9ErrMwlddshO8906MYsy8Bz4nIsZGAdSu6gCksfacLRxDfq-399kauOATBxDriVVynSnfTBL8CXBSVbfv--p2jXfTEVjzKFdWg10CJAKGc-YNrz-uuF6oH373x7ZyTjabZ-I8i-oGU0Hu0CTf5MszGQgzqpW8m62KGFhF1nLnCgaaU4kHeg-mJIn9aoQ_4t3GHPS_kx1WLW6sGpUltfyFMz2rls8800dnXG1NPnOaAbsnKGbVgefUFpTm3CneFyK_M93qY5SMMHPn33iY0

{
    "EpisodeTitle": "Episode 1",
    "Duration": "1:30:00","EpisodeNumber": 1,
    "EpisodeNumber": 10,
    "Category": "Business",
    "Listeners": 1000
}
